FROM sphinxdoc/sphinx AS build

WORKDIR /src

RUN pip install sphinx_rtd_theme

ADD docs ./docs
RUN cd docs && make html

FROM nginx:stable-alpine
COPY --from=build /src/docs/build/html /usr/share/nginx/html
#ADD ./docs/build/html /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
