version: '2.4'
services:
  frontend:
    container_name: dash
    ports:
      - "8033:80"
    networks:
      - web
      - default
    build:
      context: ./frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tim-dash.rule=Host(`dashboard.${DOMAIN}`)"
      - "traefik.http.routers.tim-dash.entrypoints=websecure"
      - "traefik.http.routers.tim-dash.tls.certresolver=le"
      - "traefik.http.routers.tim-dash.tls=true"
      - "traefik.http.services.tim-dash.loadbalancer.server.port=80"

networks:
  web:
    external: true
    name: web
